### ISSUE TITLE
How about using git fetch instead?

### ISSUE THREAD

**Issue by rofrol** [siedentop/git-quickfix#11]
for example this is how I update default branch without switching to it:

`git fetch -f . "$REMOTE_AND_BRANCH":"$BRANCH"`

or with the script `git fm`

Source https://github.com/rofrol/dotfiles/blob/master/bin/git-fm

**Comment by siedentop** [comment]
Hi @rofrol ,

thanks for taking the time to report a possible improvement.

Thanks for the suggestion to use git fetch to get the default branch! 

I'd like to avoid a remote call for the git operation. But maybe I can cache this information. 

I'll think about it and come back to this.

Best regards, Christoph

**Comment by rofrol** [comment]
but this is local call `git fetch -f .` when using dot `.`
