### ISSUE TITLE
Make --keep the default?

### ISSUE THREAD

**Issue by sharkdp** [siedentop/git-quickfix#8]
Thank you for creating this. This is a really useful git addon!

> Unless --keep is provided, the quickfix commit will be removed.

This came as a surprise to me (because I didn't finish reading the documentation before trying the tool :roll_eyes:). I would argue that `--keep` should be the default. Even if the "quickfix" commit does not naturally belong into my feature branch (topic wise), I usually like to keep them around. Because it's often not just a typo or documentation change, but an actual bugfix that I need in order to develop my feature. And I don't see any downsides (except maybe "cosmetic" ones), because my branch will later cleanly merge into master if that bugfix has already made it to master.

I realize this would be a breaking change, but maybe it's worth discussing. Otherwise, I'm also fine with (usually) providing `--keep` of course.

**Comment by betwo** [comment]
I usually also use the `--keep` flag, so I would be fine with this being the default. 
Maybe a solution could be to add an "auto-keep" option in the git config and default this to `false` to make it a non-breaking change?

**Comment by siedentop** [comment]
Hi both of you, thanks for bring this up.

I thought a lot of the design, when originally coming up with the idea and implementation. But some thoughts are better than others ;) 

My concern was (incorrectly) that this would lead to too many merge conflicts. I hear that I'm wrong on this. 

So, I'd gladly change the option to be `--keep` by default. 

If someone else is reading this later, and would like `--keep` to be off by default, please voice your concern, and we can make it configurable via the git config.

**Comment by siedentop** [comment]
Question, @sharkdp & @betwo : What would you call the new option: `--no-keep` or `--remove`? 

I went with `--remove` for now. Let me know your thoughts.

**Comment by sharkdp** [comment]
I like `--remove`. Another option might be `--drop` which would be in line with the git terminology to drop a commit upon (interactive) rebasing. Which is what users would probably do without git-quickfix(?).
