### ISSUE TITLE
Rename --stash to --autostash?

### ISSUE THREAD

**Issue by sharkdp** [siedentop/git-quickfix#9]
The `--stash` functionality of `git-quickfix` is similar to `git`s own `--autostash` option for a few commands. It doesn't simply `stash (push)` the local changes, it also `stash pop`s afterwards.

From `man git-rebase`:
```
       --autostash, --no-autostash
           Automatically create a temporary stash entry before the
           operation begins, and apply it after the operation ends. This
           means that you can run rebase on a dirty worktree. However, use
           with care: the final stash application after a successful
           rebase might result in non-trivial conflicts.
```

So you could consider renaming `--stash` to `--autostash`. Or maybe rename and provide `--stash` as an alias (to avoid breaking changes).

**Comment by betwo** [comment]
Originally the option was called `--autostash` (when introduced here: https://github.com/siedentop/git-quickfix/pull/2), but sadly I have forgotten why this was renamed to `--stash` on the PR.
Do you remember, @siedentop?

**Comment by siedentop** [comment]
Sorry for the late response. Thanks for raising the issue, @sharkdp. Thanks for your comment, @betwo. I don't think the option was ever `--autostash` in the original PR.

Let's rename the option to `--autostash`.
